version: '3.9'
services:
  web:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' -e production"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/prtimes-scraping
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: mysql:5.6
    platform: linux/amd64
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-time-zone=Asia/Tokyo
    volumes:
      - db-volume:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password_000
      MYSQL_DATABASE: root
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
volumes:
  db-volume: